<template>
  <noscript>
    <iframe
      src="https://www.googletagmanager.com/ns.html?id=GTM-M5XNS4B9"
      height="0"
      width="0"
      style="display:none;visibility:hidden"
    ></iframe>
  </noscript>
</template> 